version: '3.8'
services:
  web:
    build: .
    depends_on:
      - db
    env_file: .env.example
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: